.\" (C) Copyright 2013 Sean Reifschneider, RealGo, Inc.
.\"     <sean+opensource@realgo.com>,
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BACKUP-CLIENT 1 "October 30, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
backup-client \- authorized_keys shim for securing rsync-over-ssh backups
.SH SYNOPSIS
.B backup-client
.RI "[-- [rsyncoptions]]"
.SH DESCRIPTION
This is a shim, to be used in the SSH
.B authorized_keys
file.  It allows calling rsync, with most options fixed, but allows the
remote end to control the "\fB--compress\fP" and "\fB--bwlimit\fP" options.
.PP
It is placed in the "command" prefix on an SSH public key in the
"authorized_keys" file, and given the rsync options you would like to force.
It will then detect whether the remote end called it with the "--compress" or
"--bwlimit" options and prepend them to the resulting rsync command-line.  It
then execs that rsync command.
.SH OPTIONS
This command currently takes no options directly.  If called with no arguments,
it runs rsync with a standard set of arguments for sending the full
file-system.  Otherwise, it must be given two dashes (`-') as its first
option, then remaining options are passed directly to rsync.
.SH HELPERS
Any scripts located in "\fB/etc/backup-client/helpers.d\fP" are run
before rsync is started, with the argument "start".  The scripts are run
in sorted order by script name.  After the rsync exits, these scripts
are run in reverse order with the argument "stop".
.PP
In the event that a script exits with a non-zero exit-code, the remaining
start scripts are not run, and rsync is not run.  Any scripts that were
run with "start" are run as normal, with "stop".
.PP
When a helper exits with non-zero, the rsync is not run so that the helper
script failure is obvious rather than silently being swallowed.
.SH SEE ALSO
.BR rsync (1),
.BR ssh (1).
.br
Full documentation is available in the README.md file or at
https://github.com/realgo/backup-client.
