#!/usr/bin/env python
#
#  Backup client program that wraps rsync and allows the server to control some
#  options which rsync doesn't.  It can also run some plugins to do things like
#  database backups.

import os
import sys
import syslog
syslog.openlog(os.path.basename(sys.argv[0]))


def get_program_path():
    '''Get the full path to the Python program that is running.
    This is used for re-invoking the program under sudo, so it needs to track
    down the path to the program that was run, by following any relative
    pathing or searching the path.
    '''
    return os.path.abspath(sys.argv[0])


def length_read(fp, max_length=10000):
    data = ''
    while len(data) < 10 and ':' not in data:
        tmp = fp.read(1)
        if not tmp:
            syslog.syslog('Invalid input to length_read')
            sys.exit(1)
        data += tmp

    length, data = data.split(':', 1)
    length = int(length)

    if length > max_length:
        syslog.syslog(
            'Requested read length {0} greater than max {1}'
            .format(length, max_length))
        sys.exit(1)

    while len(data) < length:
        tmp = fp.read(length - len(data))
        if not tmp:
            syslog.syslog('Incomplete read in length_read')
            sys.exit(1)
        data += tmp

    return data


def run_as_root():
    if os.getuid() != 0:
        os.execvp(
            'sudo', ['sudo', '-n', get_program_path()] + list(sys.argv[1:]))
        syslog.syslog('Failed to exec sudo, probably need to fix sudoers')
        sys.exit(1)


def main():
    run_as_root()
    print 'Got root:', os.getuid()
    print 'length_read():', length_read(sys.stdin)

if __name__ == '__main__':
    main()
