Document: backup-client
Title: Debian backup-client Manual
Author: <insert document author here>
Abstract: This manual describes what backup-client is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/backup-client/backup-client.sgml.gz

Format: postscript
Files: /usr/share/doc/backup-client/backup-client.ps.gz

Format: text
Files: /usr/share/doc/backup-client/backup-client.text.gz

Format: HTML
Index: /usr/share/doc/backup-client/html/index.html
Files: /usr/share/doc/backup-client/html/*.html
